// Import the necessary modules and components
import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, ButtonGroup, Heading, Text } from "@chakra-ui/react";
import { Card, CardHeader, CardBody, CardFooter } from "@chakra-ui/react";

// Define the font subset for Inter
const inter = Inter({ subsets: ["latin"] });

// Define a functional component for a card that displays a plant's information
function MyCard(props) {
	// Import the router from Next.js
	const router = useRouter();

	// Handle clicks on the card by navigating to the plant page
	const handleCardClick = (e) => {
		console.log("Card clicked");
		router.push("/plant");
	};

	// Handle clicks on the "Water Plant" button by sending a PUT request to the server
	const handleButtonClick = (plantId) => {
		const requestOptions = {
			method: "PUT",
		};
		fetch("http://localhost:4000/plant/" + plantId, requestOptions)
			.then((response) => response.json())
			.then((data) => {});
	};

	// Render the card with the plant's information and "Water Plant" button
	return (
		<Card margin={10} onClick={handleCardClick}>
			<CardHeader>
				<Heading size='md'>{props.title}</Heading>
			</CardHeader>
			<CardBody>
				<Text fontSize={"sm"}>{props.description}</Text>
				<Text fontSize={"xs"}>
					Watered last on this day: {props.lastWatered}
				</Text>
				<Button
					colorScheme={"cyan"}
					onClick={(e) => {
						e.stopPropagation();
						handleButtonClick(props.plantId);
					}}
				>
					Water Plant
				</Button>
			</CardBody>
		</Card>
	);
}

// Define the main component for the homepage
export default function Home() {
	// Set up state for the list of plants
	const [plants, setPlants] = useState([]);

	// Fetch the list of plants from the server
	async function getPlants() {
		fetch("http://localhost:4000/plant")
			.then((response) => response.json())
			.then((data) => setPlants(data));
	}

	// Use the useEffect hook to fetch the plant data when the component mounts
	useEffect(() => {
		getPlants();
	}, []);

	// Render the page with the plant information cards
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Heading margin={5}>Plant Tracker</Heading>
				{plants.map(function (item, index) {
					return (
						<MyCard
							plantId={item._id}
							title={item.title}
							description={item.description}
							lastWatered={item.lastWatered}
						/>
					);
				})}
			</main>
		</>
	);
}
