import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, ButtonGroup, Heading, Text } from "@chakra-ui/react";
import { Card, CardHeader, CardBody, CardFooter } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

import { useRouter } from "next/router";
import { useEffect, useState } from "react";

function MyCard(props) {
	const router = useRouter();
	const handleCardClick = (e) => {
		console.log("Card clicked");
		router.push("/plant");
	};
	const handleButtonClick = (plantId) => {
		const requestOptions = {
			method: "PUT",
		};
		fetch("http://localhost:4000/plant/" + plantId, requestOptions)
			.then((response) => response.json())
			.then((data) => {});
	};

	return (
		<Card margin={10} onClick={handleCardClick}>
			<CardHeader>
				<Heading size='md'>{props.title}</Heading>
			</CardHeader>
			<CardBody>
				<Text fontSize={"sm"}>{props.description}</Text>
				<Text fontSize={"xs"}>
					Watered last on this day: {props.lastWatered}
				</Text>
				<Button
					colorScheme={"cyan"}
					onClick={(e) => {
						e.stopPropagation();
						handleButtonClick(props.plantId);
					}}
				>
					Water Plant
				</Button>
			</CardBody>
		</Card>
	);
}

export default function Home() {
	const [plants, setPlants] = useState([]);
	async function getPlants() {
		fetch("http://localhost:4000/plant")
			.then((response) => response.json())
			.then((data) => setPlants(data));
	}

	useEffect(() => {
		getPlants();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Heading margin={5}>Plant Tracker</Heading>
				{plants.map(function (item, index) {
					return (
						<MyCard
							plantId={item._id}
							title={item.title}
							description={item.description}
							lastWatered={item.lastWatered}
						/>
					);
				})}
			</main>
		</>
	);
}
