import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, ButtonGroup, Heading, Text } from "@chakra-ui/react";
import { Card, CardHeader, CardBody, CardFooter } from "@chakra-ui/react";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function PlantPage() {
	const router = useRouter();
	const handleClick = (e) => {
		e.preventDefault();
		router.push("/");
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Heading margin={5}>Plant</Heading>
				<Button margin={10} onClick={handleClick}>
					Go Back
				</Button>
			</main>
		</>
	);
}
